name = "Minecraft+"
author = "Khazoda"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95da51ee70ae36dace9a3e6fb51ca8be44a63dbc39fdf1281274d7eae7203f49"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
