name = "June +"
author = "Khazoda"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ea1fdf7825e94ac8c2dcfb62ec604cd7f230743109eabedfd8f9e547fc40141"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
