name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b78ad16c907b2cc1c6dcb5f9d752b1065f8d94f5b65a00abaedacf20d2d28d3"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
