name = "June +"
author = "Khazoda"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59afa0d4e8751d4214a8f2a8441c89060c00724467fa2a3adf4760d8d7e781b7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
