name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ebd8d365867dbd87637bc9135009add04b19492dde0fd20992ae529a536e9ab"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
