name = "June +"
author = "Khazoda"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49d95cbe07bada825cfc9626bac2ffac0bb74fb754664e07b031cf8a0e544c97"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
