name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a4d2f658fd341140508ae047450f10bfba2da7c82abfc55fd45c3948f841007"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
