name = "Minecraft+"
author = "Khazoda"
version = "1.1.33"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b03a2dc259d4e2638b869b5b30ffe926ccaa01c931d6db7c5bd8da0357dee5f7"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
