name = "Minecraft+"
author = "Khazoda"
version = "1.1.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f43921df5d6282e3df9d66476e1f4be2521329323fd06b7556a23bd3c36f4099"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
