name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "188e5b61a79511fd1275e4d277de936df5f63507d36f7cc397b0e5a843a30301"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
