name = "June +"
author = "Khazoda"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3922dec4a5d6de0550c2d00125baf7b8e741094e25b9e43a4959f7461d797814"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
