name = "Minecraft+"
author = "Khazoda"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76abf750e92a2e12cb892f8caae094d4162d11f36b85f8659ecd1b25df1e847a"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
