name = "Minecraft+"
author = "Khazoda"
version = "1.1.25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "286cf750fd4bede4114fb144ae770049ce6f037b3f980822afb118fb385e1099"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
