name = "Minecraft+"
author = "Khazoda"
version = "1.3.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4e5c10a40a864a3912bc42ef0764c810d7a829ab6d14e3b534a8d7afb992962"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21", "1.21.1"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["global_packs/required_resources/*"]
