name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7277463978384b0946ca4795764fe16abff139b92d3f10d58a82a176e4e905ec"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
