name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce309a83b5cb4ce9bcafc9c62e1651c9462bed50ed5666b8438bdd74c9e12ad"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
