name = "June +"
author = "Khazoda"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2d6f7c1831e37f904e9e66a6abf9afa9e9d8b08dcb5efbdd852607f9c4394ba"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
