name = "Minecraft+"
author = "Khazoda"
version = "1.1.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6635cc9f54993a38212f46cf82e958e481bec508ee52050316886e068b1fbde"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
