name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14042a538c571d9011f278761735cf549bd11a390b7e214b1219d555d41d2a9f"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
