name = "Minecraft+"
author = "Khazoda"
version = "1.1.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfb013c78e214a64bc5c4b1719952dc5e4f9f363852fcf120639ecc256aa3439"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
