name = "Minecraft+"
author = "Khazoda"
version = "1.3.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dd469d952e52a1e5dbeee9057095d96b0c47fe93473759abeac15f3e4a7a5bb"

[versions]
fabric = "0.16.9"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21"]
