name = "Minecraft+"
author = "Khazoda"
version = "1.1.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95e8ec9b3015d143e2b900a9cac782fcc0805e05ba31dcd1b90e257d0a679cc9"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21-rc.1"]
