name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f23ea0206af8d658ad6dc545d6acc202c2cb8a7399185f5eb333cb9d64f3239"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
