name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d1e199ac4221c569cbac45944e32e95ff85ea3bda0be60ecd73182562f41890"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
