name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0bd22ecd6efd6a721bcdc9eda75996e79ae12b4899a68bcaff62955e6fb51c5"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
