name = "June +"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a407d344406a2106ba9d7ad3fc613f155b5fe56c3da97b8e0ae975abdb3f36b"

[versions]
minecraft = "1.20.6"
quilt = "0.26.0-beta.1"
