name = "Minecraft+"
author = "Khazoda"
version = "1.3.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42da71f1bbf900aad43327d59af4a86b4407bf24fb129418470ab2e6317ba4d2"

[versions]
fabric = "0.16.9"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21"]
